// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn mul_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], out) {
        (TensorValue::F8(a), TensorValue::F8(b), TensorValue::F8(out)) => super::kernels::normal::mul_f8_normal(a, b, out),
        (TensorValue::BF16(a), TensorValue::BF16(b), TensorValue::BF16(out)) => super::kernels::normal::mul_bf16_normal(a, b, out),
        (TensorValue::F16(a), TensorValue::F16(b), TensorValue::F16(out)) => super::kernels::normal::mul_f16_normal(a, b, out),
        (TensorValue::F32(a), TensorValue::F32(b), TensorValue::F32(out)) => super::kernels::normal::mul_f32_normal(a, b, out),
        (TensorValue::F64(a), TensorValue::F64(b), TensorValue::F64(out)) => super::kernels::normal::mul_f64_normal(a, b, out),
        (TensorValue::I8(a), TensorValue::I8(b), TensorValue::I8(out)) => super::kernels::normal::mul_i8_normal(a, b, out),
        (TensorValue::I16(a), TensorValue::I16(b), TensorValue::I16(out)) => super::kernels::normal::mul_i16_normal(a, b, out),
        (TensorValue::I32(a), TensorValue::I32(b), TensorValue::I32(out)) => super::kernels::normal::mul_i32_normal(a, b, out),
        (TensorValue::I64(a), TensorValue::I64(b), TensorValue::I64(out)) => super::kernels::normal::mul_i64_normal(a, b, out),
        (TensorValue::U8(a), TensorValue::U8(b), TensorValue::U8(out)) => super::kernels::normal::mul_u8_normal(a, b, out),
        (TensorValue::U16(a), TensorValue::U16(b), TensorValue::U16(out)) => super::kernels::normal::mul_u16_normal(a, b, out),
        (TensorValue::U32(a), TensorValue::U32(b), TensorValue::U32(out)) => super::kernels::normal::mul_u32_normal(a, b, out),
        (TensorValue::U64(a), TensorValue::U64(b), TensorValue::U64(out)) => super::kernels::normal::mul_u64_normal(a, b, out),
        (TensorValue::Bool(a), TensorValue::Bool(b), TensorValue::Bool(out)) => super::kernels::normal::mul_bool_normal(a, b, out),
        (TensorValue::Bitset(a), TensorValue::Bitset(b), TensorValue::Bitset(out)) => super::kernels::normal::mul_bitset_normal(a, b, out),
        (TensorValue::I1(a), TensorValue::I1(b), TensorValue::I1(out)) => super::kernels::packed::mul_i1_packed(a, b, out),
        (TensorValue::I2(a), TensorValue::I2(b), TensorValue::I2(out)) => super::kernels::packed::mul_i2_packed(a, b, out),
        (TensorValue::I4(a), TensorValue::I4(b), TensorValue::I4(out)) => super::kernels::packed::mul_i4_packed(a, b, out),
        (TensorValue::U1(a), TensorValue::U1(b), TensorValue::U1(out)) => super::kernels::packed::mul_u1_packed(a, b, out),
        (TensorValue::U2(a), TensorValue::U2(b), TensorValue::U2(out)) => super::kernels::packed::mul_u2_packed(a, b, out),
        (TensorValue::U4(a), TensorValue::U4(b), TensorValue::U4(out)) => super::kernels::packed::mul_u4_packed(a, b, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn mul_inplace_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (out, &inputs[1]) {
        (TensorValue::F8(a), TensorValue::F8(b)) => super::kernels::normal::mul_f8_inplace(a, b),
        (TensorValue::BF16(a), TensorValue::BF16(b)) => super::kernels::normal::mul_bf16_inplace(a, b),
        (TensorValue::F16(a), TensorValue::F16(b)) => super::kernels::normal::mul_f16_inplace(a, b),
        (TensorValue::F32(a), TensorValue::F32(b)) => super::kernels::normal::mul_f32_inplace(a, b),
        (TensorValue::F64(a), TensorValue::F64(b)) => super::kernels::normal::mul_f64_inplace(a, b),
        (TensorValue::I8(a), TensorValue::I8(b)) => super::kernels::normal::mul_i8_inplace(a, b),
        (TensorValue::I16(a), TensorValue::I16(b)) => super::kernels::normal::mul_i16_inplace(a, b),
        (TensorValue::I32(a), TensorValue::I32(b)) => super::kernels::normal::mul_i32_inplace(a, b),
        (TensorValue::I64(a), TensorValue::I64(b)) => super::kernels::normal::mul_i64_inplace(a, b),
        (TensorValue::U8(a), TensorValue::U8(b)) => super::kernels::normal::mul_u8_inplace(a, b),
        (TensorValue::U16(a), TensorValue::U16(b)) => super::kernels::normal::mul_u16_inplace(a, b),
        (TensorValue::U32(a), TensorValue::U32(b)) => super::kernels::normal::mul_u32_inplace(a, b),
        (TensorValue::U64(a), TensorValue::U64(b)) => super::kernels::normal::mul_u64_inplace(a, b),
        (TensorValue::Bool(a), TensorValue::Bool(b)) => super::kernels::normal::mul_bool_inplace(a, b),
        (TensorValue::Bitset(a), TensorValue::Bitset(b)) => super::kernels::normal::mul_bitset_inplace(a, b),
        (TensorValue::I1(a), TensorValue::I1(b)) => super::kernels::packed::mul_i1_packed_inplace(a, b),
        (TensorValue::I2(a), TensorValue::I2(b)) => super::kernels::packed::mul_i2_packed_inplace(a, b),
        (TensorValue::I4(a), TensorValue::I4(b)) => super::kernels::packed::mul_i4_packed_inplace(a, b),
        (TensorValue::U1(a), TensorValue::U1(b)) => super::kernels::packed::mul_u1_packed_inplace(a, b),
        (TensorValue::U2(a), TensorValue::U2(b)) => super::kernels::packed::mul_u2_packed_inplace(a, b),
        (TensorValue::U4(a), TensorValue::U4(b)) => super::kernels::packed::mul_u4_packed_inplace(a, b),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn mul_accumulate_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], out) {
        (TensorValue::I1(a), TensorValue::I1(b), TensorValue::I8(out)) => super::kernels::accumulate::mul_i1_accumulate_i8(a, b, out),
        (TensorValue::I1(a), TensorValue::I1(b), TensorValue::I16(out)) => super::kernels::accumulate::mul_i1_accumulate_i16(a, b, out),
        (TensorValue::I1(a), TensorValue::I1(b), TensorValue::I32(out)) => super::kernels::accumulate::mul_i1_accumulate_i32(a, b, out),
        (TensorValue::I1(a), TensorValue::I1(b), TensorValue::I64(out)) => super::kernels::accumulate::mul_i1_accumulate_i64(a, b, out),
        (TensorValue::I2(a), TensorValue::I2(b), TensorValue::I8(out)) => super::kernels::accumulate::mul_i2_accumulate_i8(a, b, out),
        (TensorValue::I2(a), TensorValue::I2(b), TensorValue::I16(out)) => super::kernels::accumulate::mul_i2_accumulate_i16(a, b, out),
        (TensorValue::I2(a), TensorValue::I2(b), TensorValue::I32(out)) => super::kernels::accumulate::mul_i2_accumulate_i32(a, b, out),
        (TensorValue::I2(a), TensorValue::I2(b), TensorValue::I64(out)) => super::kernels::accumulate::mul_i2_accumulate_i64(a, b, out),
        (TensorValue::I4(a), TensorValue::I4(b), TensorValue::I8(out)) => super::kernels::accumulate::mul_i4_accumulate_i8(a, b, out),
        (TensorValue::I4(a), TensorValue::I4(b), TensorValue::I16(out)) => super::kernels::accumulate::mul_i4_accumulate_i16(a, b, out),
        (TensorValue::I4(a), TensorValue::I4(b), TensorValue::I32(out)) => super::kernels::accumulate::mul_i4_accumulate_i32(a, b, out),
        (TensorValue::I4(a), TensorValue::I4(b), TensorValue::I64(out)) => super::kernels::accumulate::mul_i4_accumulate_i64(a, b, out),
        (TensorValue::I8(a), TensorValue::I8(b), TensorValue::I16(out)) => super::kernels::accumulate::mul_i8_accumulate_i16(a, b, out),
        (TensorValue::I8(a), TensorValue::I8(b), TensorValue::I32(out)) => super::kernels::accumulate::mul_i8_accumulate_i32(a, b, out),
        (TensorValue::I8(a), TensorValue::I8(b), TensorValue::I64(out)) => super::kernels::accumulate::mul_i8_accumulate_i64(a, b, out),
        (TensorValue::I16(a), TensorValue::I16(b), TensorValue::I32(out)) => super::kernels::accumulate::mul_i16_accumulate_i32(a, b, out),
        (TensorValue::I16(a), TensorValue::I16(b), TensorValue::I64(out)) => super::kernels::accumulate::mul_i16_accumulate_i64(a, b, out),
        (TensorValue::I32(a), TensorValue::I32(b), TensorValue::I64(out)) => super::kernels::accumulate::mul_i32_accumulate_i64(a, b, out),
        (TensorValue::U1(a), TensorValue::U1(b), TensorValue::U8(out)) => super::kernels::accumulate::mul_u1_accumulate_u8(a, b, out),
        (TensorValue::U1(a), TensorValue::U1(b), TensorValue::U16(out)) => super::kernels::accumulate::mul_u1_accumulate_u16(a, b, out),
        (TensorValue::U1(a), TensorValue::U1(b), TensorValue::U32(out)) => super::kernels::accumulate::mul_u1_accumulate_u32(a, b, out),
        (TensorValue::U1(a), TensorValue::U1(b), TensorValue::U64(out)) => super::kernels::accumulate::mul_u1_accumulate_u64(a, b, out),
        (TensorValue::U2(a), TensorValue::U2(b), TensorValue::U8(out)) => super::kernels::accumulate::mul_u2_accumulate_u8(a, b, out),
        (TensorValue::U2(a), TensorValue::U2(b), TensorValue::U16(out)) => super::kernels::accumulate::mul_u2_accumulate_u16(a, b, out),
        (TensorValue::U2(a), TensorValue::U2(b), TensorValue::U32(out)) => super::kernels::accumulate::mul_u2_accumulate_u32(a, b, out),
        (TensorValue::U2(a), TensorValue::U2(b), TensorValue::U64(out)) => super::kernels::accumulate::mul_u2_accumulate_u64(a, b, out),
        (TensorValue::U4(a), TensorValue::U4(b), TensorValue::U8(out)) => super::kernels::accumulate::mul_u4_accumulate_u8(a, b, out),
        (TensorValue::U4(a), TensorValue::U4(b), TensorValue::U16(out)) => super::kernels::accumulate::mul_u4_accumulate_u16(a, b, out),
        (TensorValue::U4(a), TensorValue::U4(b), TensorValue::U32(out)) => super::kernels::accumulate::mul_u4_accumulate_u32(a, b, out),
        (TensorValue::U4(a), TensorValue::U4(b), TensorValue::U64(out)) => super::kernels::accumulate::mul_u4_accumulate_u64(a, b, out),
        (TensorValue::U8(a), TensorValue::U8(b), TensorValue::U16(out)) => super::kernels::accumulate::mul_u8_accumulate_u16(a, b, out),
        (TensorValue::U8(a), TensorValue::U8(b), TensorValue::U32(out)) => super::kernels::accumulate::mul_u8_accumulate_u32(a, b, out),
        (TensorValue::U8(a), TensorValue::U8(b), TensorValue::U64(out)) => super::kernels::accumulate::mul_u8_accumulate_u64(a, b, out),
        (TensorValue::U16(a), TensorValue::U16(b), TensorValue::U32(out)) => super::kernels::accumulate::mul_u16_accumulate_u32(a, b, out),
        (TensorValue::U16(a), TensorValue::U16(b), TensorValue::U64(out)) => super::kernels::accumulate::mul_u16_accumulate_u64(a, b, out),
        (TensorValue::U32(a), TensorValue::U32(b), TensorValue::U64(out)) => super::kernels::accumulate::mul_u32_accumulate_u64(a, b, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}
