// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn relu_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a), TensorValue::F8(out)) => super::kernels::normal::relu_f8_normal(_attrs, a, out),
        (TensorValue::BF16(a), TensorValue::BF16(out)) => super::kernels::normal::relu_bf16_normal(_attrs, a, out),
        (TensorValue::F16(a), TensorValue::F16(out)) => super::kernels::normal::relu_f16_normal(_attrs, a, out),
        (TensorValue::F32(a), TensorValue::F32(out)) => super::kernels::normal::relu_f32_normal(_attrs, a, out),
        (TensorValue::F64(a), TensorValue::F64(out)) => super::kernels::normal::relu_f64_normal(_attrs, a, out),
        (TensorValue::I4(a), TensorValue::I4(out)) => super::kernels::packed::relu_i4_packed(_attrs, a, out),
        (TensorValue::I8(a), TensorValue::I8(out)) => super::kernels::normal::relu_i8_normal(_attrs, a, out),
        (TensorValue::I16(a), TensorValue::I16(out)) => super::kernels::normal::relu_i16_normal(_attrs, a, out),
        (TensorValue::I32(a), TensorValue::I32(out)) => super::kernels::normal::relu_i32_normal(_attrs, a, out),
        (TensorValue::I64(a), TensorValue::I64(out)) => super::kernels::normal::relu_i64_normal(_attrs, a, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn relu_inplace_dispatch(_attrs: &OpAttrs, _inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match out {
        TensorValue::F8(a) => super::kernels::normal::relu_f8_inplace(_attrs, a),
        TensorValue::BF16(a) => super::kernels::normal::relu_bf16_inplace(_attrs, a),
        TensorValue::F16(a) => super::kernels::normal::relu_f16_inplace(_attrs, a),
        TensorValue::F32(a) => super::kernels::normal::relu_f32_inplace(_attrs, a),
        TensorValue::F64(a) => super::kernels::normal::relu_f64_inplace(_attrs, a),
        TensorValue::I4(a) => super::kernels::packed::relu_i4_packed_inplace(_attrs, a),
        TensorValue::I8(a) => super::kernels::normal::relu_i8_inplace(_attrs, a),
        TensorValue::I16(a) => super::kernels::normal::relu_i16_inplace(_attrs, a),
        TensorValue::I32(a) => super::kernels::normal::relu_i32_inplace(_attrs, a),
        TensorValue::I64(a) => super::kernels::normal::relu_i64_inplace(_attrs, a),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

