// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn is_finite_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a), TensorValue::Bool(out)) => super::kernels::normal::is_finite_f8_normal(a, out),
        (TensorValue::BF16(a), TensorValue::Bool(out)) => super::kernels::normal::is_finite_bf16_normal(a, out),
        (TensorValue::F16(a), TensorValue::Bool(out)) => super::kernels::normal::is_finite_f16_normal(a, out),
        (TensorValue::F32(a), TensorValue::Bool(out)) => super::kernels::normal::is_finite_f32_normal(a, out),
        (TensorValue::F64(a), TensorValue::Bool(out)) => super::kernels::normal::is_finite_f64_normal(a, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

