#![allow(unused_imports)]

mod op_attrs;
mod op_dtypes;
mod op_defs;

pub use op_attrs::{
    OpAttrDef, OpAttrType, ScalarAttrKind, ACC_ATTR, ALPHA_ATTR, AXES_ATTR, AXIS_ATTR, BITS_ATTR,
    CLAMP_MAX_ATTR, DIV_BY_ZERO_MASK_ATTR, KEEPDIMS_ATTR, MAX_ATTR, MIN_ATTR,
    NUMERIC_SCALAR_KINDS, ROUNDING_MODE_ATTR, SATURATE_ATTR, SELECT_FIRST_ATTR, TO_ATTR,
    VALUE_ATTR,
};
pub use op_dtypes::{
    OpDTypeSupport, ACC_INT_PAIRS, ABS_DTYPE_SUPPORT, ADD_DTYPE_SUPPORT, AND_DTYPE_SUPPORT,
    ARGMAX_AXIS_DTYPE_SUPPORT, ARGMIN_AXIS_DTYPE_SUPPORT, CAST_DTYPE_SUPPORT, CAST_OUTPUT_DTYPES,
    CEIL_DTYPE_SUPPORT, CLAMP_DTYPE_SUPPORT, DIV_DTYPE_SUPPORT, EQ_DTYPE_SUPPORT,
    FILL_DTYPE_SUPPORT, FILTER_DTYPE_SUPPORT, FLOOR_DIV_DTYPE_SUPPORT, FLOOR_DTYPE_SUPPORT,
    FMA_DTYPE_SUPPORT, GE_DTYPE_SUPPORT, GT_DTYPE_SUPPORT, IS_FINITE_DTYPE_SUPPORT,
    IS_INF_DTYPE_SUPPORT, IS_NAN_DTYPE_SUPPORT, IS_NEG_DTYPE_SUPPORT, LE_DTYPE_SUPPORT,
    LT_DTYPE_SUPPORT, MATMUL_DTYPE_SUPPORT, MAX_AXIS_DTYPE_SUPPORT, MAX_DTYPE_SUPPORT,
    MEAN_AXIS_DTYPE_SUPPORT, MIN_AXIS_DTYPE_SUPPORT, MIN_DTYPE_SUPPORT, MUL_DTYPE_SUPPORT,
    NE_DTYPE_SUPPORT, NEG_DTYPE_SUPPORT, NOT_DTYPE_SUPPORT, OR_DTYPE_SUPPORT,
    POPCOUNT_DTYPE_SUPPORT, PROD_AXIS_DTYPE_SUPPORT, RECIP_DTYPE_SUPPORT, RELU_DTYPE_SUPPORT,
    REM_DTYPE_SUPPORT, ROUND_DTYPE_SUPPORT, SHL_DTYPE_SUPPORT, SHR_DTYPE_SUPPORT,
    SIGN_DTYPE_SUPPORT, SUB_DTYPE_SUPPORT, SUM_AXIS_DTYPE_SUPPORT, TRUNC_DTYPE_SUPPORT,
    XOR_DTYPE_SUPPORT,
};
pub use op_defs::{
    acc_dtype, op_schema, AccumulateSupport, BroadcastSupport, InplaceSupport, InputArity,
    OpSchema, OutputArity, TypeRule, OPS,
};
