use crate::ops::registry::{KernelFn, OpKey, OpMode};
use crate::tensor::DType;

use super::wrappers::*;

pub static ENTRIES: &[(OpKey, KernelFn)] = &[
    (op_key(OpMode::Normal, false, DType::F8E5M2, DType::F8E5M2), add_normal_f8),
    (op_key(OpMode::Normal, true, DType::F8E5M2, DType::F8E5M2), add_normal_f8),
    (op_key(OpMode::Inplace, false, DType::F8E5M2, DType::F8E5M2), add_inplace_f8),
    (op_key(OpMode::Inplace, true, DType::F8E5M2, DType::F8E5M2), add_inplace_f8),
    (op_key(OpMode::Normal, false, DType::BF16, DType::BF16), add_normal_bf16),
    (op_key(OpMode::Normal, true, DType::BF16, DType::BF16), add_normal_bf16),
    (op_key(OpMode::Inplace, false, DType::BF16, DType::BF16), add_inplace_bf16),
    (op_key(OpMode::Inplace, true, DType::BF16, DType::BF16), add_inplace_bf16),
    (op_key(OpMode::Normal, false, DType::F16, DType::F16), add_normal_f16),
    (op_key(OpMode::Normal, true, DType::F16, DType::F16), add_normal_f16),
    (op_key(OpMode::Inplace, false, DType::F16, DType::F16), add_inplace_f16),
    (op_key(OpMode::Inplace, true, DType::F16, DType::F16), add_inplace_f16),
    (op_key(OpMode::Normal, false, DType::F32, DType::F32), add_normal_f32),
    (op_key(OpMode::Normal, true, DType::F32, DType::F32), add_normal_f32),
    (op_key(OpMode::Inplace, false, DType::F32, DType::F32), add_inplace_f32),
    (op_key(OpMode::Inplace, true, DType::F32, DType::F32), add_inplace_f32),
    (op_key(OpMode::Normal, false, DType::F64, DType::F64), add_normal_f64),
    (op_key(OpMode::Normal, true, DType::F64, DType::F64), add_normal_f64),
    (op_key(OpMode::Inplace, false, DType::F64, DType::F64), add_inplace_f64),
    (op_key(OpMode::Inplace, true, DType::F64, DType::F64), add_inplace_f64),
    (op_key(OpMode::Normal, false, DType::I1, DType::I1), add_normal_i1),
    (op_key(OpMode::Normal, true, DType::I1, DType::I1), add_normal_i1),
    (op_key(OpMode::Inplace, false, DType::I1, DType::I1), add_inplace_i1),
    (op_key(OpMode::Inplace, true, DType::I1, DType::I1), add_inplace_i1),
    (op_key(OpMode::Normal, false, DType::I2, DType::I2), add_normal_i2),
    (op_key(OpMode::Normal, true, DType::I2, DType::I2), add_normal_i2),
    (op_key(OpMode::Inplace, false, DType::I2, DType::I2), add_inplace_i2),
    (op_key(OpMode::Inplace, true, DType::I2, DType::I2), add_inplace_i2),
    (op_key(OpMode::Normal, false, DType::I4, DType::I4), add_normal_i4),
    (op_key(OpMode::Normal, true, DType::I4, DType::I4), add_normal_i4),
    (op_key(OpMode::Inplace, false, DType::I4, DType::I4), add_inplace_i4),
    (op_key(OpMode::Inplace, true, DType::I4, DType::I4), add_inplace_i4),
    (op_key(OpMode::Normal, false, DType::I8, DType::I8), add_normal_i8),
    (op_key(OpMode::Normal, true, DType::I8, DType::I8), add_normal_i8),
    (op_key(OpMode::Inplace, false, DType::I8, DType::I8), add_inplace_i8),
    (op_key(OpMode::Inplace, true, DType::I8, DType::I8), add_inplace_i8),
    (op_key(OpMode::Normal, false, DType::I16, DType::I16), add_normal_i16),
    (op_key(OpMode::Normal, true, DType::I16, DType::I16), add_normal_i16),
    (op_key(OpMode::Inplace, false, DType::I16, DType::I16), add_inplace_i16),
    (op_key(OpMode::Inplace, true, DType::I16, DType::I16), add_inplace_i16),
    (op_key(OpMode::Normal, false, DType::I32, DType::I32), add_normal_i32),
    (op_key(OpMode::Normal, true, DType::I32, DType::I32), add_normal_i32),
    (op_key(OpMode::Inplace, false, DType::I32, DType::I32), add_inplace_i32),
    (op_key(OpMode::Inplace, true, DType::I32, DType::I32), add_inplace_i32),
    (op_key(OpMode::Normal, false, DType::I64, DType::I64), add_normal_i64),
    (op_key(OpMode::Normal, true, DType::I64, DType::I64), add_normal_i64),
    (op_key(OpMode::Inplace, false, DType::I64, DType::I64), add_inplace_i64),
    (op_key(OpMode::Inplace, true, DType::I64, DType::I64), add_inplace_i64),
    (op_key(OpMode::Normal, false, DType::U1, DType::U1), add_normal_u1),
    (op_key(OpMode::Normal, true, DType::U1, DType::U1), add_normal_u1),
    (op_key(OpMode::Inplace, false, DType::U1, DType::U1), add_inplace_u1),
    (op_key(OpMode::Inplace, true, DType::U1, DType::U1), add_inplace_u1),
    (op_key(OpMode::Normal, false, DType::U2, DType::U2), add_normal_u2),
    (op_key(OpMode::Normal, true, DType::U2, DType::U2), add_normal_u2),
    (op_key(OpMode::Inplace, false, DType::U2, DType::U2), add_inplace_u2),
    (op_key(OpMode::Inplace, true, DType::U2, DType::U2), add_inplace_u2),
    (op_key(OpMode::Normal, false, DType::U4, DType::U4), add_normal_u4),
    (op_key(OpMode::Normal, true, DType::U4, DType::U4), add_normal_u4),
    (op_key(OpMode::Inplace, false, DType::U4, DType::U4), add_inplace_u4),
    (op_key(OpMode::Inplace, true, DType::U4, DType::U4), add_inplace_u4),
    (op_key(OpMode::Normal, false, DType::U8, DType::U8), add_normal_u8),
    (op_key(OpMode::Normal, true, DType::U8, DType::U8), add_normal_u8),
    (op_key(OpMode::Inplace, false, DType::U8, DType::U8), add_inplace_u8),
    (op_key(OpMode::Inplace, true, DType::U8, DType::U8), add_inplace_u8),
    (op_key(OpMode::Normal, false, DType::U16, DType::U16), add_normal_u16),
    (op_key(OpMode::Normal, true, DType::U16, DType::U16), add_normal_u16),
    (op_key(OpMode::Inplace, false, DType::U16, DType::U16), add_inplace_u16),
    (op_key(OpMode::Inplace, true, DType::U16, DType::U16), add_inplace_u16),
    (op_key(OpMode::Normal, false, DType::U32, DType::U32), add_normal_u32),
    (op_key(OpMode::Normal, true, DType::U32, DType::U32), add_normal_u32),
    (op_key(OpMode::Inplace, false, DType::U32, DType::U32), add_inplace_u32),
    (op_key(OpMode::Inplace, true, DType::U32, DType::U32), add_inplace_u32),
    (op_key(OpMode::Normal, false, DType::U64, DType::U64), add_normal_u64),
    (op_key(OpMode::Normal, true, DType::U64, DType::U64), add_normal_u64),
    (op_key(OpMode::Inplace, false, DType::U64, DType::U64), add_inplace_u64),
    (op_key(OpMode::Inplace, true, DType::U64, DType::U64), add_inplace_u64),
    (op_key(OpMode::Normal, false, DType::Bool, DType::Bool), add_normal_bool),
    (op_key(OpMode::Normal, true, DType::Bool, DType::Bool), add_normal_bool),
    (op_key(OpMode::Inplace, false, DType::Bool, DType::Bool), add_inplace_bool),
    (op_key(OpMode::Inplace, true, DType::Bool, DType::Bool), add_inplace_bool),
    (op_key(OpMode::Normal, false, DType::Bitset, DType::Bitset), add_normal_bitset),
    (op_key(OpMode::Normal, true, DType::Bitset, DType::Bitset), add_normal_bitset),
    (op_key(OpMode::Inplace, false, DType::Bitset, DType::Bitset), add_inplace_bitset),
    (op_key(OpMode::Inplace, true, DType::Bitset, DType::Bitset), add_inplace_bitset),
    (op_key(OpMode::Accumulate, false, DType::I8, DType::I8), add_accumulate_i8_i8),
    (op_key(OpMode::Accumulate, true, DType::I8, DType::I8), add_accumulate_i8_i8),
    (op_key(OpMode::Accumulate, false, DType::I8, DType::I16), add_accumulate_i8_i16),
    (op_key(OpMode::Accumulate, true, DType::I8, DType::I16), add_accumulate_i8_i16),
    (op_key(OpMode::Accumulate, false, DType::I8, DType::I32), add_accumulate_i8_i32),
    (op_key(OpMode::Accumulate, true, DType::I8, DType::I32), add_accumulate_i8_i32),
    (op_key(OpMode::Accumulate, false, DType::I8, DType::I64), add_accumulate_i8_i64),
    (op_key(OpMode::Accumulate, true, DType::I8, DType::I64), add_accumulate_i8_i64),
    (op_key(OpMode::Accumulate, false, DType::I16, DType::I8), add_accumulate_i16_i8),
    (op_key(OpMode::Accumulate, true, DType::I16, DType::I8), add_accumulate_i16_i8),
    (op_key(OpMode::Accumulate, false, DType::I16, DType::I16), add_accumulate_i16_i16),
    (op_key(OpMode::Accumulate, true, DType::I16, DType::I16), add_accumulate_i16_i16),
    (op_key(OpMode::Accumulate, false, DType::I16, DType::I32), add_accumulate_i16_i32),
    (op_key(OpMode::Accumulate, true, DType::I16, DType::I32), add_accumulate_i16_i32),
    (op_key(OpMode::Accumulate, false, DType::I16, DType::I64), add_accumulate_i16_i64),
    (op_key(OpMode::Accumulate, true, DType::I16, DType::I64), add_accumulate_i16_i64),
    (op_key(OpMode::Accumulate, false, DType::I32, DType::I8), add_accumulate_i32_i8),
    (op_key(OpMode::Accumulate, true, DType::I32, DType::I8), add_accumulate_i32_i8),
    (op_key(OpMode::Accumulate, false, DType::I32, DType::I16), add_accumulate_i32_i16),
    (op_key(OpMode::Accumulate, true, DType::I32, DType::I16), add_accumulate_i32_i16),
    (op_key(OpMode::Accumulate, false, DType::I32, DType::I32), add_accumulate_i32_i32),
    (op_key(OpMode::Accumulate, true, DType::I32, DType::I32), add_accumulate_i32_i32),
    (op_key(OpMode::Accumulate, false, DType::I32, DType::I64), add_accumulate_i32_i64),
    (op_key(OpMode::Accumulate, true, DType::I32, DType::I64), add_accumulate_i32_i64),
    (op_key(OpMode::Accumulate, false, DType::I64, DType::I8), add_accumulate_i64_i8),
    (op_key(OpMode::Accumulate, true, DType::I64, DType::I8), add_accumulate_i64_i8),
    (op_key(OpMode::Accumulate, false, DType::I64, DType::I16), add_accumulate_i64_i16),
    (op_key(OpMode::Accumulate, true, DType::I64, DType::I16), add_accumulate_i64_i16),
    (op_key(OpMode::Accumulate, false, DType::I64, DType::I32), add_accumulate_i64_i32),
    (op_key(OpMode::Accumulate, true, DType::I64, DType::I32), add_accumulate_i64_i32),
    (op_key(OpMode::Accumulate, false, DType::I64, DType::I64), add_accumulate_i64_i64),
    (op_key(OpMode::Accumulate, true, DType::I64, DType::I64), add_accumulate_i64_i64),
    (op_key(OpMode::Accumulate, false, DType::U8, DType::U8), add_accumulate_u8_u8),
    (op_key(OpMode::Accumulate, true, DType::U8, DType::U8), add_accumulate_u8_u8),
    (op_key(OpMode::Accumulate, false, DType::U8, DType::U16), add_accumulate_u8_u16),
    (op_key(OpMode::Accumulate, true, DType::U8, DType::U16), add_accumulate_u8_u16),
    (op_key(OpMode::Accumulate, false, DType::U8, DType::U32), add_accumulate_u8_u32),
    (op_key(OpMode::Accumulate, true, DType::U8, DType::U32), add_accumulate_u8_u32),
    (op_key(OpMode::Accumulate, false, DType::U8, DType::U64), add_accumulate_u8_u64),
    (op_key(OpMode::Accumulate, true, DType::U8, DType::U64), add_accumulate_u8_u64),
    (op_key(OpMode::Accumulate, false, DType::U16, DType::U8), add_accumulate_u16_u8),
    (op_key(OpMode::Accumulate, true, DType::U16, DType::U8), add_accumulate_u16_u8),
    (op_key(OpMode::Accumulate, false, DType::U16, DType::U16), add_accumulate_u16_u16),
    (op_key(OpMode::Accumulate, true, DType::U16, DType::U16), add_accumulate_u16_u16),
    (op_key(OpMode::Accumulate, false, DType::U16, DType::U32), add_accumulate_u16_u32),
    (op_key(OpMode::Accumulate, true, DType::U16, DType::U32), add_accumulate_u16_u32),
    (op_key(OpMode::Accumulate, false, DType::U16, DType::U64), add_accumulate_u16_u64),
    (op_key(OpMode::Accumulate, true, DType::U16, DType::U64), add_accumulate_u16_u64),
    (op_key(OpMode::Accumulate, false, DType::U32, DType::U8), add_accumulate_u32_u8),
    (op_key(OpMode::Accumulate, true, DType::U32, DType::U8), add_accumulate_u32_u8),
    (op_key(OpMode::Accumulate, false, DType::U32, DType::U16), add_accumulate_u32_u16),
    (op_key(OpMode::Accumulate, true, DType::U32, DType::U16), add_accumulate_u32_u16),
    (op_key(OpMode::Accumulate, false, DType::U32, DType::U32), add_accumulate_u32_u32),
    (op_key(OpMode::Accumulate, true, DType::U32, DType::U32), add_accumulate_u32_u32),
    (op_key(OpMode::Accumulate, false, DType::U32, DType::U64), add_accumulate_u32_u64),
    (op_key(OpMode::Accumulate, true, DType::U32, DType::U64), add_accumulate_u32_u64),
    (op_key(OpMode::Accumulate, false, DType::U64, DType::U8), add_accumulate_u64_u8),
    (op_key(OpMode::Accumulate, true, DType::U64, DType::U8), add_accumulate_u64_u8),
    (op_key(OpMode::Accumulate, false, DType::U64, DType::U16), add_accumulate_u64_u16),
    (op_key(OpMode::Accumulate, true, DType::U64, DType::U16), add_accumulate_u64_u16),
    (op_key(OpMode::Accumulate, false, DType::U64, DType::U32), add_accumulate_u64_u32),
    (op_key(OpMode::Accumulate, true, DType::U64, DType::U32), add_accumulate_u64_u32),
    (op_key(OpMode::Accumulate, false, DType::U64, DType::U64), add_accumulate_u64_u64),
    (op_key(OpMode::Accumulate, true, DType::U64, DType::U64), add_accumulate_u64_u64),
];

const fn op_key(mode: OpMode, broadcast: bool, in_dtype: DType, out_dtype: DType) -> OpKey {
    OpKey {
        kind: crate::graph::OpKind::Add,
        mode,
        broadcast,
        in0: in_dtype,
        in1: Some(in_dtype),
        out0: out_dtype,
    }
}
